name: MasterCI
on:
  push:
    branches:
      - master
  pull_request:
    types: [ closed ]
    branches:
      - master
jobs:
  build_on_push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.

  build_on_pr:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: run if the pr is merged
      run:
        echo PR is merged successfully
