name: MasterCI
on:
  pull_request:
    types: [ closed ]
    branches:
      - master
jobs:
  build_test:
    runs-on: ubuntu-latest
    strategy:
       matrix:
          python-version: [3.8, 3.9]
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Run a one-line script
      id: build_job
      run: echo Hello, world!
    - name: Run a multi-line script
      id: test_job
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
  push_deploy:
    runs-on: ubuntu-latest
    strategy:
       matrix:
          python-version: [3.8]
    needs: build_test
    if: needs.build_test.result == 'failure'
    steps:
    - name: run if the pr is merged and build & test is sucessful
      run:
        echo PR is merged successfully
