name: MasterCI
on:
  push:
    branches:
      - master
  pull_request:
    types: [ closed ]
    branches:
      - master
jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      id: build_job
      run: echo Hello, world!
    - name: Run a multi-line script
      id: test_job
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
  push_deploy:
    runs-on: ubuntu-latest
    needs: build_test
    if: github.event.pull_request.merged == true && needs.build_test.result == 'success'
    steps:
    - name: run if the pr is merged and build & test is sucessful
      run:
        echo PR is merged successfully
