name: FeatureCI
on:
  push:
    branches:
      - '*'
      - '!master'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo "Only on feature branches"
    - name: Run a multi-line script
      run: |
        echo "Only on feature branches1"
        echo "Only on feature branches2"
    - name: display the id
      run: |
        echo "dicplay ${GITHUB_RUN_ID}"
        echo ${{github.run_id}}
    - name: display the ref
      run: |
        echo ${GITHUB_REF#refs/heads/}
