name: MasterCI
on:
  push:
    branches:
      - master
  pull_request:
    types: [ closed ]
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      id: build_job
      run: echo Hello, world!
    - name: Run a multi-line script
      id: test_job
      run: |
        echo Add other actions to build,
        eco test, and deploy your project.
    - name: run if the pr is merged and build & test is sucessful
      if: github.event.pull_request.merged == true && steps.build_job.outcome == 'success' && steps.test_job.outcome == 'success'
      run:
        echo PR is merged successfully
